name: Build and deploy

on:
  push:
    branches: [ mkdocs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        path: mkdocs
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Setup Git & Install dependencies
      run: |
        git config --global user.email "e.urunuela@bcbl.eu"
        git config --global user.name "eurunuela"
        python -m pip install --upgrade pip
        pip install -r mkdocs/requirements.txt
    - uses: actions/checkout@v5
      with:
        ref: master
        path: www
    - name: Clean up master
      run: |
        cd www/
        git ls-files -z | xargs -0 git rm -f
    - name: Build
      run: |
        cd mkdocs/
        mkdocs build -d ../www/

    - name: Deploy
      run: |
        cd www/
        echo -e "a\n*\nq\n"|git add -i
        git commit -am "auto: deploy new website"
        git push